### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by danyi1212** [axelrindle/github-version-checker#14]
Is there a plan to support this package for browser too?
Seems to be working only for Node.js

**Comment by axelrindle** [comment]
Not yet, but I'll put this on my to-do list.

**Comment by axelrindle** [comment]
Blocked until completion of octokit/webhooks-methods.js#45

**Comment by axelrindle** [comment]
Just a quick update: Browser support could be shipped by installing `@octokit/core.js @ v5.0.0-beta.4` which drops support for Node.sj < 18. As this would be a breaking change, I will wait until a stable release of `@octokit/core.js`.

**Comment by axelrindle** [comment]
Implemented in [38942b8](https://github.com/axelrindle/github-version-checker/commit/38942b8bb0f540ec527f8f0b4092eacd19ee7345). Will be shipped with the next release.
